import { describe, expect, it } from 'vitest'
import { accountBalance, emptyFinances, materializeRecurrences, monthlyTotals, parseMoney, validateFinances, type FinanceState, type MoneyEntry } from './finances'
const a = '00000000-0000-4000-8000-000000000001', b = '00000000-0000-4000-8000-000000000002', t = '00000000-0000-4000-8000-000000000003', r = '00000000-0000-4000-8000-000000000004'
const setup = (): FinanceState => ({ ...emptyFinances(), accounts: [{ id: a, name: 'Compte MAD', currency: 'MAD', openingMinor: 100000, openingDate: '2026-10-01', archived: false }, { id: b, name: 'Compte XOF', currency: 'XOF', openingMinor: 5000, openingDate: '2026-10-01', archived: false }] })
const entry = (patch: Partial<MoneyEntry> = {}): MoneyEntry => ({ id: t, date: '2026-10-07', type: 'expense', accountId: a, amountMinor: 12000, category: 'Logement', label: 'Loyer', status: 'booked', cancelled: false, ...patch })
describe('personal finances', () => {
  it('handles decimal MAD and whole XOF without binary rounding artifacts', () => { expect(parseMoney('12,35', 'MAD')).toBe(1235); expect(parseMoney('1200', 'XOF')).toBe(1200); expect(() => parseMoney('1.5', 'XOF')).toThrow(); expect(() => parseMoney('12.345', 'MAD')).toThrow() })
  it('keeps expected income, future operations and cancelled entries outside the available balance', () => { const state = setup(); state.entries = [entry({ type: 'income', status: 'planned' })]; expect(accountBalance(state, state.accounts[0], '2026-10-07')).toBe(100000); expect(monthlyTotals(state, '2026-10', 'MAD', 'planned').income).toBe(12000); state.entries = [entry({ date: '2026-10-08' })]; expect(accountBalance(state, state.accounts[0], '2026-10-07')).toBe(100000); state.entries = [entry({ cancelled: true })]; expect(accountBalance(state, state.accounts[0], '2026-10-07')).toBe(100000) })
  it('records explicit FX transfers on both accounts without inflating income or expenses', () => { const state = setup(); state.entries = [entry({ type: 'transfer', destinationId: b, destinationMinor: 7500 })]; validateFinances(state); expect(accountBalance(state, state.accounts[0], '2026-10-07')).toBe(88000); expect(accountBalance(state, state.accounts[1], '2026-10-07')).toBe(12500); expect(monthlyTotals(state, '2026-10', 'MAD', 'booked')).toEqual({ income: 0, expense: 0 }) })
  it('rejects ambiguous FX, self-transfers, dates before opening and duplicate identifiers', () => { const state = setup(); state.entries = [entry({ type: 'transfer', destinationId: b })]; expect(() => validateFinances(state)).toThrow(); state.entries = [entry({ type: 'transfer', destinationId: a, destinationMinor: 12000 })]; expect(() => validateFinances(state)).toThrow(); state.entries = [entry({ date: '2026-09-01' })]; expect(() => validateFinances(state)).toThrow(); state.entries = [entry(), entry()]; expect(() => validateFinances(state)).toThrow() })
  it('requires equal amounts for transfers in one currency', () => { const state = setup(); state.accounts[1].currency = 'MAD'; state.entries = [entry({ type: 'transfer', destinationId: b, destinationMinor: 12500 })]; expect(() => validateFinances(state)).toThrow(); state.entries[0].destinationMinor = 12000; expect(() => validateFinances(state)).not.toThrow() })
  it('materializes month-end recurrences once, including when paid or cancelled', () => { let state = setup(); state.recurrences = [{ id: r, accountId: a, type: 'expense', amountMinor: 2000, category: 'Abonnements', label: 'Internet', day: 31, active: true }]; state = materializeRecurrences(state, '2027-02', () => t); expect(state.entries[0].date).toBe('2027-02-28'); state.entries[0].status = 'booked'; state.entries[0].cancelled = true; expect(materializeRecurrences(state, '2027-02', () => b).entries).toHaveLength(1) })
  it('validates a backup before allowing financial state replacement', () => { expect(() => validateFinances({ version: 1, accounts: [] })).toThrow(); const state = setup(); state.entries = [entry()]; expect(() => validateFinances(state)).not.toThrow(); expect(accountBalance(state, state.accounts[0], '2026-09-30')).toBeNull() })
})
